#!/usr/bin/env bash
# 打开不同 配置 的 emacs 方式, 但基本只用默认的

export PATH=$HOME/miniconda3/envs/usr/bin:$PATH
version=${version:-30.1}
em=~/codes/emacs-${version}/src/emacs
emc=~/codes/emacs-${version}/lib-src/emacsclient
if [ "$1" == 'default' ]; then
    if [ ! -z $2 ]; then
        $em --name "$2"
    else
        $em
    fi
	#systemctl restart --user emacsanywhere.service
elif [ "$1" == 'client' ]; then
    $emc -c
elif [ "$1" == 'test' ]; then
	$em --init-directory ~/.wemacs_test/
else 
	$em
fi
